GitHub Actionsでビルドするイメージタグを詳細に設定する Fixes #113

diff --git a/.github/workflows/conoha.yml b/.github/workflows/conoha.yml
--- a/.github/workflows/conoha.yml
+++ b/.github/workflows/conoha.yml
@@ -4,14 +4,12 @@ on:
   push:
     branches:
       - master
+      - staging
   workflow_dispatch:
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
-
-env:
-  CONTAINER_NAME: mikubot
 
 jobs:
   check:
@@ -53,6 +51,9 @@ jobs:
     permissions:
       contents: read
       packages: write
+    outputs:
+      IMAGE_TAG_FOR_PULL: ${{steps.tag.outputs.TAG_FOR_PULL}}
+      CONTAINER_NAME: ${{steps.container_name.outputs.CONTAINER_NAME}}
 
     steps:
       - name: Checkout
@@ -68,13 +69,40 @@ jobs:
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Set container name
+        id: container_name
+        run: |
+          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
+            echo "CONTAINER_NAME=mikubot" >> "$GITHUB_OUTPUT"
+          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
+            echo "CONTAINER_NAME=mikubot-staging" >> "$GITHUB_OUTPUT"
+          else
+            echo "[WARNING] Invalid branch: ${{ github.ref }}. Skipping deployment."
+            exit 1
+          fi
+
+      - name: Create image tag
+        id: tag
+        if: steps.container_name.outcome.success
+        run: |
+          SHA=${{github.sha}}
+          TAG="${{vars.IMAGE}}:$(TZ=UTC-9 date +'%Y%m')-${SHA:0:7}"
+          echo "TAG_FOR_PULL=$TAG" >> "$GITHUB_OUTPUT"
+          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
+            LATEST="${{vars.IMAGE}}:latest"
+            echo "TAGS=$TAG,$LATEST" >> "$GITHUB_OUTPUT"
+          else
+            echo "TAGS=$TAG" >> "$GITHUB_OUTPUT"
+          fi
+          echo "Generated image tag: $TAG"
+
       - name: Build and push
         uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # v6.3.0
         with:
           context: .
           file: ./Dockerfile
           push: true
-          tags: ${{ vars.IMAGE_TAG }}
+          tags: ${{ steps.tag.outputs.TAGS }}
           cache-from: type=gha
           cache-to: type=gha, mode=max
 
@@ -96,16 +124,16 @@ jobs:
           # always remove old container: https://stackoverflow.com/questions/34228864/stop-and-delete-docker-container-if-its-running
           script: |
             echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
-            docker pull ${{ vars.IMAGE_TAG }}
-            docker stop ${{ env.CONTAINER_NAME }} || true && docker rm ${{ env.CONTAINER_NAME }} || true
+            docker pull ${{ needs.build.outputs.IMAGE_TAG_FOR_PULL }}
+            docker stop ${{ needs.build.outputs.CONTAINER_NAME }} || true && docker rm ${{ needs.build.outputs.CONTAINER_NAME }} || true
             docker run \
               -d \
-              --name ${{env.CONTAINER_NAME}} \
+              --name ${{ needs.build.outputs.CONTAINER_NAME }} \
               --env DISCORD_BOT_TOKEN=${{secrets.DISCORD_TOKEN}} \
               --env LOG_CHANNEL_ID=${{vars.LOG_CHANNEL_ID}} \
               --env NOTION_TOKEN=${{secrets.NOTION_TOKEN}} \
               --env NOTION_DOMAIN=${{vars.NOTION_DOMAIN}} \
               --env SENTRY_DSN=${{secrets.SENTRY_DSN}} \
-              ${{ vars.IMAGE_TAG }}
+              ${{ needs.build.outputs.IMAGE_TAG_FOR_PULL }}
             docker image prune -f
           script_stop: true
