chore: Update Docker CI workflow to set detailed image tags for builds

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -27,12 +27,36 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0
 
+      - name: Create image tag
+        id: tag
+        run: |
+          SHA=${{github.sha}}
+          TAG="${{vars.IMAGE}}:$(TZ=UTC-9 date +'%Y%m')-${SHA:0:7}"
+          echo "TAG_FOR_PULL=$TAG" >> "$GITHUB_OUTPUT"
+
+          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
+
+            LATEST="${{vars.IMAGE}}:latest"
+            echo "TAGS=$TAG,$LATEST" >> "$GITHUB_OUTPUT"
+            echo "IS_STAGING=FALSE" >> "$GITHUB_OUTPUT
+
+          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
+
+            echo "TAGS=$TAG" >> "$GITHUB_OUTPUT"
+            echo "IS_STAGING=TRUE" >> "$GITHUB_OUTPUT"
+
+          else
+            echo "[WARNING] Invalid branch: ${{ github.ref }}. Skipping deployment."
+            exit 1
+          fi
+          echo "Generated image tag: $TAG"
+
       - name: Build
         uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # v6.3.0
         with:
           context: .
           file: ./Dockerfile
           push: false
-          tags: ${{ vars.IMAGE_TAG }}
+          tags: ${{ steps.tag.outputs.TAGS }}
           cache-from: type=gha
           cache-to: type=gha, mode=max
