chore: Update Conoha workflow to use conoha-check and conoha-setup

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -15,7 +15,38 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  docker-build-check:
+  docker-ci-setup:
+    runs-on: ubuntu-22.04
+    permissions:
+      contents: read
+    timeout-minutes: 5
+    outputs:
+      ENVIRONMENT: ${{ steps.output.outputs.ENVIRONMENT }}
+
+    steps:
+      - name: staging
+        if: ${{ github.ref == 'refs/heads/staging' }}
+        run: |
+          echo "ENVIRONMENT=staging" >> "$GITHUB_ENV"
+
+      - name: production
+        if: ${{ github.ref == 'refs/heads/master' }}
+        run: |
+          echo "ENVIRONMENT=production" >> "$GITHUB_ENV"
+
+      - name: Error
+        if: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/staging' }}
+        run: |
+          echo "[ERROR] Invalid branch: ${{ github.ref }}. Skipping deployment."
+          exit 1
+
+      - name: Output environment
+        id: output
+        run: |
+          echo "ENVIRONMENT=${{ env.ENVIRONMENT }}" >> "$GITHUB_OUTPUT"
+
+  docker-ci:
+    needs: docker-ci-setup
     runs-on: ubuntu-22.04
     permissions:
       contents: read
@@ -37,20 +68,13 @@ jobs:
           TAG="${{vars.IMAGE}}:$(TZ=UTC-9 date +'%Y%m')-${SHA:0:7}"
           echo "TAG_FOR_PULL=${TAG}" >> "$GITHUB_OUTPUT"
 
-          if [ "${TARGET_REF}" = "refs/heads/master" ]; then
+          if [ "${{ needs.docker-ci-setup.outputs.ENVIRONMENT }}" = "production" ]; then
 
             LATEST="${{vars.IMAGE}}:latest"
             echo "TAGS=${TAG},${LATEST}" >> "$GITHUB_OUTPUT"
-            echo "IS_STAGING=FALSE" >> "$GITHUB_OUTPUT"
-
-          elif [ "${TARGET_REF}" = "refs/heads/staging" ]; then
-
-            echo "TAGS=${TAG}" >> "$GITHUB_OUTPUT"
-            echo "IS_STAGING=TRUE" >> "$GITHUB_OUTPUT"
 
           else
-            echo "[WARNING] Invalid target branch: ${TARGET_REF}. Skipping deployment."
-            exit 1
+            echo "TAGS=${TAG}" >> "$GITHUB_OUTPUT"
           fi
           echo "Generated image tag: ${TAG}"
 
